# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-18 02:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerpage', '0003_rentdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentdata',
            name='end',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='rentdata',
            name='start',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
